### ISSUE TITLE
Symbol not found error

### ISSUE THREAD

**Issue by dilawar** [aviralg/moogli#11]
Moogli compiles and link on MacOSX now, but there is still a issue:

```
 dlopen(/usr/local/lib/python2.7/site-packages/moogli/core/_moogli.so, 2): Symbol not found: __ZThn248_N9osgViewer14GraphicsWindow13requestRedrawEv
```

_moogli.so linking with `osgViewer`  library.

**Comment by dilawar** [comment]
This is an issue with `opencenegraph-3.4.0` which is default on brew. Need to add 3.2.0 as dependency in moogli brew file.

**Comment by dilawar** [comment]
No osg library export the above symbol, on ubuntu, they do. 

       find /usr/local/ -name '*.so*' -exec nm -g -A {} \; | grep "requestRedraw"

**Comment by dilawar** [comment]
In framework, with `dylib`, there is a symbol. Trying that now.

**Comment by aviralg** [comment]
@dilawar - stop spamming. You don't have to provide a minute by minute update. Once you have investigated the issue,  provide all the details in a single post in a logically coherent manner.
